// <auto-generated />
using System;
using Factory.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Factory.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251118091552_updateBatch")]
    partial class updateBatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Factory.Data.Modules.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Factory.Data.Modules.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Factory.Data.Modules.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("IncomingMaterial")
                        .HasColumnType("double precision");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OutgoingMaterial")
                        .HasColumnType("double precision");

                    b.Property<double>("PricePerOneKilo")
                        .HasColumnType("double precision");

                    b.Property<int?>("batchId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("batchId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Factory.Data.Modules.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("IncomingProduct")
                        .HasColumnType("double precision");

                    b.Property<double>("OutgoingProduct")
                        .HasColumnType("double precision");

                    b.Property<double>("PricePerOneKilo")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Factory.Data.Modules.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Accountid");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Factory.Data.Modules.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer");

                    b.Property<string>("TraderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Accountid");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("Factory.Data.Modules.Treasury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("MoneyForTrader")
                        .HasColumnType("double precision");

                    b.Property<double>("MoneyFromSeller")
                        .HasColumnType("double precision");

                    b.Property<double>("OpenAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("Sallary")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalExpenses")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Treasury");
                });

            modelBuilder.Entity("Factory.Data.Modules.batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRun")
                        .HasColumnType("boolean");

                    b.Property<int?>("Productid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Productid");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Factory.Data.Modules.Material", b =>
                {
                    b.HasOne("Factory.Data.Modules.batch", null)
                        .WithMany("Materials")
                        .HasForeignKey("batchId");
                });

            modelBuilder.Entity("Factory.Data.Modules.Seller", b =>
                {
                    b.HasOne("Factory.Data.Modules.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Factory.Data.Modules.Trader", b =>
                {
                    b.HasOne("Factory.Data.Modules.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Factory.Data.Modules.batch", b =>
                {
                    b.HasOne("Factory.Data.Modules.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Productid");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Factory.Data.Modules.batch", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
