// <auto-generated />
using Factory.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Factory.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251102191812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Factory.Data.Modules.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Factory.Data.Modules.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Accountid");

                    b.ToTable("sellers");
                });

            modelBuilder.Entity("Factory.Data.Modules.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accountid")
                        .HasColumnType("integer");

                    b.Property<string>("TraderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Accountid");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("Factory.Data.Modules.Seller", b =>
                {
                    b.HasOne("Factory.Data.Modules.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Factory.Data.Modules.Trader", b =>
                {
                    b.HasOne("Factory.Data.Modules.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Accountid");

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
